### ISSUE TITLE
Hi there, about can't upload

### ISSUE THREAD

**Issue by cliuxinxin** [doccano/doccano-client#86]
https://github.com/doccano/doccano-client/issues/16
https://github.com/doccano/doccano-client/issues/13
https://github.com/doccano/doccano-client/issues/50

I know this issue is discovered.

I tried the beta , it's not working.

because label data is the iteration work

upload data is important to the whole process 

I hope you guys can solve it asap

Thank you for all of your work. It's making my job easy.

**Comment by mritonia** [comment]
What was the error that you saw? I was having an issue uploading data as well, but I found a way to fix it for my use case (thanks to [this answer](https://github.com/doccano/doccano-client/issues/79#issuecomment-1206039835) on a previous question). The first thing I did was installed from the github repo directly (from the master branch) instead of the pypi install. The latest _release_ didn't work for me -- also the latest release was last year.

Try
```
pip install https://github.com/doccano/doccano-client/archive/refs/heads/master.zip
```
I know this is not best practice for maintaining your versioning, but it was the easiest way for me to deal with.
And I was able to make the connection to the client like so

```
from doccano_api_client import DoccanoClient

# instantiate a client and log in to a Doccano instance
doccano_client = DoccanoClient(
    'https://my-deployment.url.here',
    'user_name',
    'password'
)
```
the _key_ breakthrough that I made is that the `url` for the deployment is critical. For me, I had inadvertently added an extra `/` at the end of the URL that was causing JSON decode errors. Once I was connected, then uploading via binary file was very simple (in my case, I was uploading the image).
```
image_filepath = open(my image path, 'rb')
file_format = "ImageFile"
resp = doccano_client.post_doc_upload_binary(project_id=1, files=[image_filepath], format='ImageFile')
```

**Comment by cliuxinxin** [comment]
Thank you , I uesed python 3.7.9 it is not working. I update to 3.10, it is working. But when I import the jsonl with relation. It is not working, but still solve me some problem. Thank you
